version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-supersegura}
      POSTGRES_DB: calls
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./bd/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
